/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TimeLock } from "./TimeLock";
export * as factories from "./factories";
export { TimeLock__factory } from "./factories/TimeLock__factory";
