/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TimelockInterface } from "./TimelockInterface";
export * as factories from "./factories";
export { TimelockInterface__factory } from "./factories/TimelockInterface__factory";
