import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Web3Modal from "web3modal";
import { ethers } from "ethers";
import WalletConnectProvider from "@walletconnect/web3-provider";

const Home: NextPage = () => {
  const providerOptions = {
    /* See Provider Options Section */
    walletconnect: {
      package: WalletConnectProvider, // required
      options: {
        infuraId: "INFURA_ID", // required
      },
    },
  };
  const web3Modal = new Web3Modal({
    cacheProvider: true, // optional
    providerOptions, // required
  });
  let provider: ethers.providers.Web3Provider;
  const handleWalletConnect = async () => {
    const instance = await web3Modal.connect();
    provider = instance;
    console.log(provider);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="p-0 m-0 w-full h-16 backdrop-blur-sm bg-teal-500 flex flex-row overflow-hidden">
        <div className="text-3xl p-4 ml-10 text-white font-extrabold">
          THE DAO
        </div>
        <button
          onClick={handleWalletConnect}
          className="h-8 my-auto w-60 text-2xl rounded-xl  bg-green-300/40 relative left-[70%] text-white hover:bg-green-500"
        >
          connect wallet
        </button>
      </header>
      <main>
        <div className="text-3xl text-emerald-800">
          Good to be writing React code again
        </div>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
