/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20VoteInterface } from "./ERC20VoteInterface";
export * as factories from "./factories";
export { ERC20VoteInterface__factory } from "./factories/ERC20VoteInterface__factory";
