/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DAOMIGovernance } from "./DAOMIGovernance";
export * as factories from "./factories";
export { DAOMIGovernance__factory } from "./factories/DAOMIGovernance__factory";
