/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernanceERC20 } from "./GovernanceERC20";
export * as factories from "./factories";
export { GovernanceERC20__factory } from "./factories/GovernanceERC20__factory";
